# <font style="color:rgb(50,120,229)">Overview </font>

We have already discussed about how an image is formed and how it is stored. In this module, we will dive into the code and check out what are the functions available in OpenCV for manipulating images.

We will cover the following:
1. Image I/O - Read, Write & Display an image
2. Image Properties - color, channels, shape, image structure
3. Creating new images, accessing pixels and region of interest (ROI)

# <font style="color:rgb(50,120,229)">Import Libraries</font>

In [1]:
# Import libraries
import cv2                  # OpenCV library
import numpy as np              # Numpy library
from dataPath import DATA_PATH        # dataPath module for data path to the image file 
import matplotlib.pyplot as plt         # Matplotlib library
%matplotlib inline                    

In [2]:
import matplotlib
matplotlib.rcParams['figure.figsize'] = (6.0, 6.0)       # set default size of plots b/c I like big plots :)
matplotlib.rcParams['image.cmap'] = 'gray'              # Use gray color map for all plots, When image has shape (M,N,3) or (M,N,4), the values in img1 are interpreted as RGB or RGBA values. In this case the cmap is ignored.

# <font style="color:rgb(50,120,229)">Reading an Image</font>
OpenCV allows reading different types of images (JPG, PNG, etc). You can load grayscale images colour images or you can also load images with Alpha channel (Alpha channel will be discussed in a later section). It uses the [**`imread`**](https://docs.opencv.org/4.1.0/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56) function which has the following syntax:

### <font style="color:rgb(8,133,37)">Function Syntax </font>
``` python
retval	=	cv2.imread(	filename[, flags]	)
```

It has **2 arguments**:

1. `retval` is the image if it is successfully loaded. Otherwise it is `None`. This may happen if the filename is wrong or the file is corrupt.
2. `Path of the image file`: This can be an **absolute** or **relative** path. This is a **mandatory argument**.
3. `Flags`: These flags are used to read an image in a particular format (for example, grayscale/color/with alpha channel). This is an **optional argument** with a default value of `cv2.IMREAD_COLOR` or `1` which loads the image as a color image.

Before we proceed with some examples, let's also have a look at the `flags` available.

**Flags**
1. **`cv2.IMREAD_GRAYSCALE`** or **`0`**: Loads image in grayscale mode
2. **`cv2.IMREAD_COLOR`** or **`1`**: Loads a color image. Any transparency of image will be neglected. It is the default flag.
3. **`cv2.IMREAD_UNCHANGED`** or **`-1`**: Loads image as such including alpha channel. Whenever using transperent png, ensure to use this option.


Let us load this image and discuss further
<img src="https://www.dropbox.com/s/ed0r779b052o0s2/number_zero.jpg?dl=1" width=100>

In [3]:
imagePath = DATA_PATH + "/images/number_zero.jpg"

# Read image in Grayscale format
testImage = cv2.imread(imagePath,0)  # 0 for grayscale - not a good practice, instead use cv2.IMREAD_GRAYSCALE
print(testImage)

[[  1   0   3   0   3   0   3   2   4   2   0]
 [  0   1   0   3   3 253 253   0   0   2   1]
 [  0   0   8   0 249 255 255 253  71   1   5]
 [  3   0   2 251 255   2   0 253 254   0   2]
 [  1   5   0 252   4   0   3   0 255   4   0]
 [  0   0   2 255   0   0   0   3 253   0   4]
 [  0   5   4 249   4   2   0   0 255   1   0]
 [  2   0   0 255   3   0   5   0 254   0   4]
 [  0   0   0 255   1   0   0   3 255   0   0]
 [  1   5   0 252   2   2   2  76 250   7   0]
 [  0   0   5   0 254   0   0 255 254   0   1]
 [  0   8   0   3 253 253 255 250   1   2   1]
 [  2   0   0   0   5   0   4   1   3   0   0]]


We print the 2-dimensional array to see what the image is. You can make out that the image signifies a `0`. Whenever cv2.imread() is used, the variable (testImage) will be a numpy array. We will discuss more about numpy arrays in the next module.

## <font style="color:rgb(50,120,229)">Intensity </font>
The values printed above are the intensity values of each pixel. 

**0 means black pixel and as the value increases, it moves towards white. A value of 255 is a white pixel.**

## <font style="color:rgb(50,120,229)">Image Properties</font>

In [4]:
print("Data type = {}\n".format(testImage.dtype))  # uint8 - unsigned integer 8 bits (0-255)
print("Object type = {}\n".format(type(testImage)))
print("Image Dimensions = {}\n".format(testImage.shape)) # (13,11) - numpy array of 13 rows and 11 columns, however, the image is 11x13 pixels

Data type = uint8

Object type = <class 'numpy.ndarray'>

Image Dimensions = (13, 11)



The following observations can be made:
1. The datatype of the loaded image is **unsigned int and the depth is 8 bit**
1. The image is just a 2-dimesional numpy array with values ranging from **0 to 255**.
1. The size or resolution is **13x11** which means **height=13 and witdh=11**. In other words, it has **13 rows and 11 columns**.


#### <font style="color:rgb(200,0,0)">NOTE</font>
It should be kept in mind that in OpenCV, size is represented as a tuple of `widthxheight` or `#columnsX#rows`. But in numpy, the shape method returns size as a tuple of `heightxwidth`.

#### What happen if we try to read this image as a color image, and whats the dimensions look like?
#### What happen if we try to read this image as a png style image?

In [5]:
# trying to read the image in color format
testImage_color = cv2.IMREAD_COLOR(imagePath)       # this will throw an error as the image is not read in color format
print(testImage_color)

TypeError: 'int' object is not callable

In [7]:
testImage_color2 = cv2.imread(imagePath,1)  # 1 for color            # output is a numpy array of 13 rows, 11 columns and 3 channels (BGR)
print(testImage_color2)

[[[  1   1   1]
  [  0   0   0]
  [  3   3   3]
  [  0   0   0]
  [  3   3   3]
  [  0   0   0]
  [  3   3   3]
  [  2   2   2]
  [  4   4   4]
  [  2   2   2]
  [  0   0   0]]

 [[  0   0   0]
  [  1   1   1]
  [  0   0   0]
  [  3   3   3]
  [  3   3   3]
  [253 253 253]
  [253 253 253]
  [  0   0   0]
  [  0   0   0]
  [  2   2   2]
  [  1   1   1]]

 [[  0   0   0]
  [  0   0   0]
  [  8   8   8]
  [  0   0   0]
  [249 249 249]
  [255 255 255]
  [255 255 255]
  [253 253 253]
  [ 71  71  71]
  [  1   1   1]
  [  5   5   5]]

 [[  3   3   3]
  [  0   0   0]
  [  2   2   2]
  [251 251 251]
  [255 255 255]
  [  2   2   2]
  [  0   0   0]
  [253 253 253]
  [254 254 254]
  [  0   0   0]
  [  2   2   2]]

 [[  1   1   1]
  [  5   5   5]
  [  0   0   0]
  [252 252 252]
  [  4   4   4]
  [  0   0   0]
  [  3   3   3]
  [  0   0   0]
  [255 255 255]
  [  4   4   4]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  2   2   2]
  [255 255 255]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0

In [8]:
print("Data type = {}\n".format(testImage_color2.dtype))       # uint8 - unsigned integer 8 bits (0-255), but 3 channels (BGR) b/c color image 
print("Object type = {}\n".format(type(testImage_color2)))     # numpy array
print("Image Dimensions = {}\n".format(testImage_color2.shape)) # (13,11,3) - numpy array of 13 rows, 11 columns and 3 channels (BGR) b/c of color image

Data type = uint8

Object type = <class 'numpy.ndarray'>

Image Dimensions = (13, 11, 3)



### Q- how to interpret the intensity value of a pixel in a color image?
A- In grayscale mode, several shades of gray are used to create a picture. There can be up to 256 shades of gray in an 8-bit picture. A grayscale image's brightness value ranges from 0 (black) to 255 (white). 

To replicate colors on screen, RGB pictures make use of three hues, or channels. The three channels in an 8-bit-per-channel picture convert to 24 bits of color information per pixel (8 bits x 3 channels). In color mode, the color is represented by a combination of three primary colors: red, green, and blue. Each of these primary colors can have a value from 0 to 255. The three channels can reproduce up to 16.7 million colors per pixel when working with 24bit pictures.

#### Examples:
The color black is represented by the combination of all three primary colors set to 0. 

The color white is represented by the combination of all three primary colors set to 255. 

The color red is represented by the combination of red set to 255, green set to 0, and blue set to 0. 

The color green is represented by the combination of red set to 0, green set to 255, and blue set to 0. 

The color blue is represented by the combination of red set to 0, green set to 0, and blue set to 255. 

The color yellow is represented by the combination of red set to 255, green set to 255, and blue set to 0. 

The color cyan is represented by the combination of red set to 0, green set to 255, and blue set to 255. 

The color magenta is represented by the combination of red set to 255, green set to 0, and blue set to 255. 

The color orange is represented by the combination of red set to 255, green set to 165, and blue set to 0. 

The color purple is represented by the combination of red set to 128, green set to 0, and blue set to 128. 

The color brown is represented by the combination of red set to 165, green set to 42, and blue set to 42. 

The color pink is represented by the combination of red set to 255, green set to 192, and blue set to 203.

The color gray is represented by the combination of red set to 128, green set to 128, and blue set to 128. 

The color silver is represented by the combination of red set to 192, green set to 192, and blue set to 192. 

The color olive is represented by the combination of red set to 128, green set to 128, and blue set to 0. 

The color maroon is represented by the combination of red set to 128, green set to 0, and blue set to 0. 

The color aqua is represented by the combination of red set to 0, green set to 255, and blue set to 255. 





#### Q- Are we trying to reduce the computation complexity and expenses when a colored image converted to greyscale image?
A- Yes, we are trying to reduce the computation complexity and expenses here compared to the same image in Color mode with 3 channels.

#### Q- Do we always need to convert a colored image to greyscale image?
A- No, we don't always need to convert a colored image to greyscale image. It depends on the application. For example, if we are trying to detect the edges of an object, we don't need to convert the image to greyscale. But if we are trying to detect the color of an object, we need to convert the image to greyscale.

#### Q- What if I try to load a colored image in grayscale mode?
A- If you try to load a colored image in grayscale mode, the image will be loaded in grayscale mode but the color information will be lost. The weights of the three channels will be added to get the grayscale value of the pixel. The weights are 0.114 for blue, 0.587 for green, and 0.299 for red. The weights are chosen to match the human perception of the relative intensity of each color. Y = 0.299 R + 0.587 G + 0.114 B





In [6]:
# trying to read the image in png format
testImage_png = cv2.IMREAD_UNCHANGED(imagePath)     # this will throw an error as the image is not read in png format
print(testImage_png)

TypeError: 'int' object is not callable

In [9]:
testImage_png2 = cv2.imread(imagePath,-1)  # -1 for png format
print(testImage_png2)                     # same as grey scale image as png format is not supported

[[  1   0   3   0   3   0   3   2   4   2   0]
 [  0   1   0   3   3 253 253   0   0   2   1]
 [  0   0   8   0 249 255 255 253  71   1   5]
 [  3   0   2 251 255   2   0 253 254   0   2]
 [  1   5   0 252   4   0   3   0 255   4   0]
 [  0   0   2 255   0   0   0   3 253   0   4]
 [  0   5   4 249   4   2   0   0 255   1   0]
 [  2   0   0 255   3   0   5   0 254   0   4]
 [  0   0   0 255   1   0   0   3 255   0   0]
 [  1   5   0 252   2   2   2  76 250   7   0]
 [  0   0   5   0 254   0   0 255 254   0   1]
 [  0   8   0   3 253 253 255 250   1   2   1]
 [  2   0   0   0   5   0   4   1   3   0   0]]


In [11]:
print("Data type = {}\n".format(testImage_png2.dtype))      # uint8 - unsigned integer 8 bits (0-255), however the image is png format with transparency channel - 4 channels (BGR + alpha)
print("Object type = {}\n".format(type(testImage_png2)))    # numpy array
print("Image Dimensions = {}\n".format(testImage_png2.shape))      


Data type = uint8

Object type = <class 'numpy.ndarray'>

Image Dimensions = (13, 11)



### Q- Why it appeas to be a representation of a grey scale image, though we tried to load it as a png image?
A- Since the loaded image is in JPEG format, it is loaded as a grayscale image. Since the alpha channel is not used in JPEG, the 4th channel is ignored. The image is loaded as a grayscale image and the alpha channel is ignored.

